### ISSUE TITLE
Update xcom version

### ISSUE THREAD

**Issue by caiiiycuk** [caiiiycuk/epicport#24]
To version 1.0

**Comment by MartinTheodoreHappel** [comment]
So, it's not updated still. I assume it's not going to happen now?

**Comment by caiiiycuk** [comment]
Yeah, I am sorry, but now I am working on js-dos project, so probably I will replace xcom with original dos version

**Comment by caiiiycuk** [comment]
Now you can play original X-Com here: https://talks.dos.zone/t/x-com-ufo-defense-1994/7309
