### ISSUE TITLE
Load a saved game terminates program

### ISSUE THREAD

**Issue by frankhei** [caiiiycuk/epicport#52]
Hi,

When I try to load a game I saved previously the programs terminates. The Error Console shows the following message and then stops functioning:
Error: ExitStatus: Program terminated with exit(0)
Source File: http://epicport.com/js/jquery-1.11.1.min.js?gQHVlrK4-jX-OmNOo0LXww
Line: 11674

I Hope this information helps to track down the problem. Would be nice if it is possible to fix the problem.

Regards,
Frank

**Comment by frankhei** [comment]
The issue occurs in the browser version of Dune 2. Tested it on OS X in Chrome, Firefox and Safari. Tested on Windows 7 in Chrome, Firefox and IE 11.

**Comment by frankhei** [comment]
The issue occurs in the browser version of Dune 2. Tested it on OS X in Chrome, Firefox and Safari. Tested on Windows 7 in Chrome, Firefox and IE 11.

**Comment by caiiiycuk** [comment]
Do you have this bug only with one saved game? Or you totally can`t save and load games? Please tell me your login that you use to play on epicport.com.
Does the game load immediately after you save it (without page reloading)?

**Comment by frankhei** [comment]
I can save multiple games. And after each save I can continue playing. But when I try to load a game the program freezes completely. I gave it time and waited long but no (saved) game was loaded. It is not possible to continue playing. A hard page reload F5 is needed to get it to work again. There is no way I'm able to load a saved game. I logged out with what I call login 1.

I tried it again with a fresh login, I call this login 2. Now I get the following error on the screen when I save a game:
Error (500)
(500): [Exception... "Component does not have requested interface" nsresult: "0x80004002 (NS_NOINTERFACE)" location: "JS frame :: http://epicport.com/js/jquery-1.11.1.min.js?gQHVlrK4-jX-OmNOo0LXww :: :: line 4" data: no]

Interestingly without a page reload I can load the game I saved before. The game does not freeze. It loads perfectly and I can play it. Then I did a page reload and logout. Login with login 2 again, and now there are no saved games in the list, the list is empty. Again a page reload. Logout and login 1. List is occupied with saved games from login 1. I try to load a game but the program freezes again.

I have the feeling we could be looking at two different issues here.

**Comment by caiiiycuk** [comment]
Can you tell me your login 1? I will check your saved games.
>Error (500)
(500): [Exception... "Component does not have requested interface" nsresult: "0x80004002 (NS_NOINTERFACE)" location: "JS frame :: http://epicport.com/js/jquery-1.11.1.min.js?gQHVlrK4-jX-OmNOo0LXww :: :: line 4" data: no]

Can you copy and paste complete stack of exception? You can read how to do this here: https://developer.chrome.com/devtools/docs/javascript-debugging#viewing-exception-stack-trace

**Comment by frankhei** [comment]
Hi Aleksander,

The first login is epicport.com.frank@alshetgaatom.com
It should contain about 10 saved games which I would love to 
have access to.

The second login is epicport.com.frank2@alshetgaatom.com
I created it for testing and it should contain two or three 
saved games which are not important. The Error 500 are related 
to the second login.

Here the stack (screenshots) for the error when trying to load a 
game with any saved game from the first login.










Hope this helps.

Regards,
Frank

**Comment by caiiiycuk** [comment]
@frankhei  looks like i forgot to attach screenshots

**Comment by frankhei** [comment]
Hi Aleksander,

It seems that for some reason the pictures in the e-mail did not 
get true. I attached them as individual files. Hope you will be 
able to see them now :)

Cheers,
Frank

**Comment by caiiiycuk** [comment]
Hi Frank,

Can you send this screenshots again directly on caiiiycuk@gmail.com. Looks
like github doesn't support attachments in emails.

2015-03-06 16:56 GMT+07:00 Frank Heijkamp <notifications@github.com>:

> Hi Aleksander,
>
> It seems that for some reason the pictures in the e-mail did not
> get true. I attached them as individual files. Hope you will be
> able to see them now :)
>
> Cheers,
> Frank
>
>
> On 06-03-15 04:43, Aleksander Guryanov wrote:
> >
> > @frankhei <https://github.com/frankhei> looks like i forgot to
> > attach screenshots
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/caiiiycuk/epicport/issues/52#issuecomment-77505912>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caiiiycuk/epicport/issues/52#issuecomment-77533803>.
>



-- 
С уважением, Гурьянов Александр

**Comment by caiiiycuk** [comment]
http://vk.com/good_whore

-- 
С уважением, Гурьянов Александр

**Comment by frankhei** [comment]
Hi Aleksander,

Your account seems to be compromised, try to renew your password. Or if the account is safe then stop sending me links about whores.

Frank

**Comment by frankhei** [comment]
Hi Aleksander,

Your account seems to be compromised, try to renew your password. Or if the account is safe then stop sending me links about whores.

Frank
