### ISSUE TITLE
Login problem on TTD

### ISSUE THREAD

**Issue by Mariam-H** [caiiiycuk/epicport#71]
Hi. 

I'm having trouble logging into TTD. Everything was working perfectly fine, until (I think) 2 days ago.
I use my LiveJournal account through ulogin.ru. After I type my username and password, I get the message "Now you can save games" but then nothing happens. It either keeps loading forever, or it crashes. I tried both Chrome and Firefox.

Would really appreciate it if someone can offer any help. Thanks!

**Comment by caiiiycuk** [comment]
Hi! Can you send me logs from browser console?

**Comment by Mariam-H** [comment]
Well, this is embarrassing. I tried to login to send you the logs and I was actually able to login successfully. So I apologize for this thread. I swear I've been trying for 2 days, I don't know how it magically worked.

Thanks so much!

**Comment by caiiiycuk** [comment]
Ok, feel free to reopen issue if problem occurs.
