### ISSUE TITLE
Dune 2 saved games

### ISSUE THREAD

**Issue by Frooz76** [caiiiycuk/epicport#79]
How can I open saved games in the browser version of Dune 2? I can't find my saved games from my last session...

**Comment by Sir-Domaine** [comment]
What is the best game like this available on Android platform Kitkat or
newer ?

  =-{ $1r D0ma!n3 }-= in 2,o17

~={ $1r D0m@!n3 }=~ in 2,o14

**Comment by randacc76** [comment]
From my experience you have to go through the initial intro, start the tutorial then you can click options > load game.

**Comment by caiiiycuk** [comment]
To load saved game you should login on epicport.com before game starts.

**Comment by caiiiycuk** [comment]
@Sir-Domaine https://epicport.com/en/dune2/android
