### ISSUE TITLE
OpenTTD won't load

### ISSUE THREAD

**Issue by elizie** [caiiiycuk/epicport#84]
Whenever I try to play OpenTTD, it gets to the main menu but it's continuously loading, the menu runs in the background but I can't click on anything because the loading icon is still there. It was fine a few days ago.

![screenshot 2017-07-20 at 3 01 52 pm](https://user-images.githubusercontent.com/30306555/28398684-76e7fc60-6d5c-11e7-9fb6-79f83325ac12.png)

**Comment by caiiiycuk** [comment]
I've checked it, and for me it works. Can you please tell me you browser version, and if possible can you copy and paste here browser console output.

**Comment by elizie** [comment]
I'm using a Chromebook, so it's google chrome. Not sure what version it is though.

**Comment by caiiiycuk** [comment]
Can you open browser console? Should be Ctrl+Shift+I

**Comment by elizie** [comment]
Got it, did you want everything that's there?

**Comment by caiiiycuk** [comment]
Please select all and paste here.

**Comment by elizie** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
ulogin.js:68 [uLogin] ulogin.js received message: ready
api.js?V7OTonz9j0OVct576HaMKw:35 pre-main prep time: 2288 ms
VM255:746 Playing song: https://epicport.com/ttd/music/gm_tt00.ogg
/xhr/storage/content/ttd?fileName=%2Fhome%2Fcaiiiycuk%2Fplay-ttd%2Fetc%2Fpr…sav&identity=epicport.com%2Fu%2Fellie05harper%40gmail.com&first_name=Ellie Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
api.js?V7OTonz9j0OVct576HaMKw:269 Creating file 'Flawood Transport, 18th Jun 1956.sav' in '/home/caiiiycuk/play-ttd/etc/preload/save/'
api.js?V7OTonz9j0OVct576HaMKw:269 Creating file 'dead, 1st Feb 1958.sav' in '/home/caiiiycuk/play-ttd/etc/preload/save/'
api.js?V7OTonz9j0OVct576HaMKw:269 Creating file 'dead, 19th May 1959.sav' in '/home/caiiiycuk/play-ttd/etc/preload/save/'
api.js?V7OTonz9j0OVct576HaMKw:269 Creating file '18 year old train, 14th Apr 1956.sav' in '/home/caiiiycuk/play-ttd/etc/preload/save/'
api.js?V7OTonz9j0OVct576HaMKw:267 Uncaught TypeError: Cannot read property 'file' of null
    at api.js?V7OTonz9j0OVct576HaMKw:267
    at async.js?L_iaJyb3dF0a2JOTr-Twqw:229
    at async.js?L_iaJyb3dF0a2JOTr-Twqw:116
    at async.js?L_iaJyb3dF0a2JOTr-Twqw:24
    at async.js?L_iaJyb3dF0a2JOTr-Twqw:226
    at async.js?L_iaJyb3dF0a2JOTr-Twqw:513
    at Object.error (api.js?V7OTonz9j0OVct576HaMKw:296)
    at j (jquery.js?PJE32IoAsa4LQf9qcFcWFQ:2)
    at Object.fireWith [as rejectWith] (jquery.js?PJE32IoAsa4LQf9qcFcWFQ:2)
    at x (jquery.js?PJE32IoAsa4LQf9qcFcWFQ:4)
(anonymous) @ api.js?V7OTonz9j0OVct576HaMKw:267
(anonymous) @ async.js?L_iaJyb3dF0a2JOTr-Twqw:229
(anonymous) @ async.js?L_iaJyb3dF0a2JOTr-Twqw:116
(anonymous) @ async.js?L_iaJyb3dF0a2JOTr-Twqw:24
(anonymous) @ async.js?L_iaJyb3dF0a2JOTr-Twqw:226
(anonymous) @ async.js?L_iaJyb3dF0a2JOTr-Twqw:513
error @ api.js?V7OTonz9j0OVct576HaMKw:296
j @ jquery.js?PJE32IoAsa4LQf9qcFcWFQ:2
fireWith @ jquery.js?PJE32IoAsa4LQf9qcFcWFQ:2
x @ jquery.js?PJE32IoAsa4LQf9qcFcWFQ:4
b @ jquery.js?PJE32IoAsa4LQf9qcFcWFQ:4
VM255:746 Playing song: https://epicport.com/ttd/music/gm_tt00.ogg

**Comment by elizie** [comment]
That's the console part.

**Comment by caiiiycuk** [comment]
The server ran out of free space, so one save game  was damaged and blocked game to start, please try now, should be fixed.

**Comment by elizie** [comment]
It's working now! Thank you!
