### ISSUE TITLE
Transferring Dune2 save games between browser and Android app

### ISSUE THREAD

**Issue by randacc76** [caiiiycuk/epicport#85]
Hello, is there any way to transfer the saved games? do they use the same save format? Love the port many thanks.

**Comment by caiiiycuk** [comment]
Thanks!! Save games are stored in OpenDUNE save files, in theory you can get games from epicport.com and open in desktop version of game. But there is no public way to do this. I can send your saves on email if you want. If so, please letter me to caiiiycuk at gmail.com

**Comment by caiiiycuk** [comment]
Ohh... You ask about transfer between web and android. Save games are fully compatible, but is I already said, there is no automatic way to transfer it.
