### ISSUE TITLE
Error: 500 . 

### ISSUE THREAD

**Issue by BeSpaleva** [caiiiycuk/epicport#90]
Iinternal server error #500 при попытке сохранить игру в X-com UFO. Проверено с различных провайдеров

**Comment by deszant** [comment]
internal server error #500 , same for me since about a week ago trying to save a game. I'm almost at the end of the game :(

**Comment by caiiiycuk** [comment]
Unfortunatelly my backend is out of free space. No idea how to fix this.

**Comment by deszant** [comment]
Hi Alexander,  today it look like it worked. I'd do some clean-up for myself but the delete save games - function does not seem working, only temporarily. Thanks for your work on this anyway, i'm sure it brings a lot of fun moments for a lots of us.
Regards,
Andras

**Comment by howlyau** [comment]
Hi, I'm having the same issue, unable to save my ttd game since about a week ago. I've been playing it at work on night shift and it's getting annoying having to start a new game every night, any idea on what's going on or at least a fix?

**Comment by caiiiycuk** [comment]
> any idea on what's going on or at least a fix

I need to migrate my backend to cloud. This is only one way to fix this problem, because now I don't have space to store save games.

**Comment by caiiiycuk** [comment]
I have 500 additional mb on server) please try if saving games now working? Please use same files to save disk space.

**Comment by caiiiycuk** [comment]
Now I fixed this issue by deleting very old saves (not accesed more than 2 years). Please try now
