### ISSUE TITLE
500 error on save

### ISSUE THREAD

**Issue by seancomeau** [caiiiycuk/epicport#92]
Playing X-Com, can't save games anymore. Tried deleting most saved games, no luck. Bummer :(

Tried Dune2, can save games there without problem. (Nevermind, internal server error on that too)

**Comment by seancomeau** [comment]
How about automatically deleting saved games older than 10 days or something?

**Comment by caiiiycuk** [comment]
Yeah this idea is good, but I am not sure, because I can delete something very important for someone :)

**Comment by caiiiycuk** [comment]
Ok, now I deleted saves that did not accessed more than two years. Please try, now should work fine.
